# This is a basic workflow to help you get started with Actions

name: Test Aborting

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test aborting 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: check for existing PR
        run: |-
          if curl -s -L  https://api.github.com/repos/kubevirt/hyperconverged-cluster-operator/pulls | jq .[].title | grep -q "Update Image Digests"; then
            echo "There is an existing PR with name 'Update Image Digests'; skipping; To run again, close the existing PR"
            echo "NO_NEW_PR=true" >> $GITHUB_ENV
          else
            echo "NEW_PR=true" >> $GITHUB_ENV
          fi

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: ${{ env.NEW_PR }}

      # Runs a set of commands using the runners shell
      - name: Hello 1
        if: ${{ env.NEW_PR }}
        run: |
          echo PR not exist yet

      # Runs a set of commands using the runners shell
      - name: Hello 2
        if: ${{ env.NO_NEW_PR }}
        run: |
          echo PR already exists
