name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Run
      run: ./update_images.sh

    - name: Regenerage
      run: |
        if ! git diff --quiet --exit-code; then
          echo "CHANGED=true" >> $GITHUB_ENV
        fi

        if [[ -f a.txt ]]; then
          echo 'AAA<<EOF' >> $GITHUB_ENV
          cat a.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          A_EXISTS=true
        fi

        if [[ -f b.txt ]]; then
          echo 'BBB<<EOF' >> $GITHUB_ENV
          cat b.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          B_EXISTS=true
        fi

        if [[ -n ${A_EXISTS} && -n ${B_EXISTS} ]]; then
          echo "A_AND_B=true" >> $GITHUB_ENV
        fi

        if [[ -n ${A_EXISTS} || -n ${B_EXISTS} ]]; then
          echo "A_OR_B=true" >> $GITHUB_ENV
        fi

    - name: a and b
      run: |
        echo ${{ env.AAA }}
        echo ${{ env.BBB }}
        echo ${{ env.A_AND_B }}
        echo ${{ env.A_OR_B }}

    - uses: peter-evans/create-pull-request@v3
      if: ${{ env.CHANGED }}
      with:
        token: ${{ secrets.BOT_SECRET }}
        commit-message: |
          Update Images
        committer: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
        title: "Update Image digests"
        body: |
          Update Image digests

          Executed by HCO Release-Bumper Bot.

          ```release-note
          Update Image digests
          ```
        assignees: nunnatsa
        reviewers: nunnatsa
        team-reviewers: owners, maintainers
        branch: Update_Image_Digest
        delete-branch: true
        signoff: true
